name: Build CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: latest-ubuntu

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: '18'

      - name: Install dependencies
        uses: npm run install

      - name: build app
        uses: npm run build